#! /bin/sh
echo run-ibis "$@"
while :
do
	case $1 in
	-c)
	    arg="$arg -c $2"
	    shift
	    shift
	    ;;
	-o)
	    arg="$arg -o $2"
	    shift
	    shift
	    ;;
	*)
	    break
	    ;;
	esac
done

nbnodes="$1"
shift

# Jar-files from library.
CLASSPATH=""
add_to_libclasspath () {
    JARFILES=`cd "$1" && ls *.jar 2>/dev/null`
    for i in ${JARFILES} ; do
        if [ -z "$LIBCLASSPATH" ] ; then
            CLASSPATH="$1/$i"
        else
            CLASSPATH="$LIBCLASSPATH:$1/$i"
        fi
    done
}

add_to_libclasspath lib

prun $arg PATH="$PATH" CLASSPATH="$CLASSPATH" -v -1 ibis-prun $nbnodes -server "$@"
