#! /bin/sh
nbnodes="$1"
shift


# Jar-files from library.
CLASSPATH=""
add_to_libclasspath () {
    JARFILES=`cd "$1" && ls *.jar 2>/dev/null`
    for i in ${JARFILES} ; do
        if [ -z "$LIBCLASSPATH" ] ; then
            CLASSPATH="$1/$i"
        else
            CLASSPATH="$LIBCLASSPATH:$1/$i"
        fi
    done
}

add_to_libclasspath lib

prun PATH="$PATH" CLASSPATH="$CLASSPATH" -v -1 ibis-prun COMMAND=/home1/codmon/ibis-mpj/bin/ibis-mpj-run $nbnodes -server "$@"
